import React, { useState } from 'react';
import { Sparkles, FileSearch, Quote, ExternalLink, Download, Copy, Check } from 'lucide-react';
import SentimentBadge from './SentimentBadge';
import EntityCard from './EntityCard';

const ResultDisplay = ({ results }) => {
  const [copied, setCopied] = useState(false);

  if (!results) return null;

  const { summary, entities, sentiment, fileName, metadata } = results;

  const handleDownload = () => {
    const dataStr = "data:text/json;charset=utf-8," + encodeURIComponent(JSON.stringify(results, null, 2));
    const downloadAnchorNode = document.createElement('a');
    downloadAnchorNode.setAttribute("href", dataStr);
    downloadAnchorNode.setAttribute("download", `analysis_${fileName.replace(/\s+/g, '_')}.json`);
    document.body.appendChild(downloadAnchorNode);
    downloadAnchorNode.click();
    downloadAnchorNode.remove();
  };

  const handleShare = () => {
    const shareText = `
Analysis Report: ${fileName}
---------------------------
Sentiment: ${sentiment.label} (Score: ${sentiment.score})

Summary:
${summary}

Entities Detected:
- Names: ${entities.names.join(', ') || 'None'}
- Organizations: ${entities.organizations.join(', ') || 'None'}
- Dates: ${entities.dates.join(', ') || 'None'}
- Amounts: ${entities.amounts.join(', ') || 'None'}

Generated by AI Document Analyzer
    `.trim();

    navigator.clipboard.writeText(shareText).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  };

  return (
    <div className="w-full max-w-5xl mx-auto space-y-8 animate-in fade-in slide-in-from-bottom-4 duration-700">
      {/* Header Info */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 p-6 rounded-2xl glass-morphism border-indigo-500/20 border-l-4">
        <div className="space-y-1">
          <div className="flex items-center gap-2">
            <h2 className="text-xl font-bold text-slate-100 flex items-center gap-2">
              <FileSearch className="w-5 h-5 text-indigo-400" />
              Analysis Result
            </h2>
            <SentimentBadge sentiment={sentiment} />
          </div>
          <p className="text-sm text-slate-400">Processed: <span className="text-indigo-300">{fileName}</span> • {metadata?.textLength} characters extracted</p>
          {!metadata?.numpyEnabled && (
            <p className="text-[10px] text-amber-500/80 font-bold uppercase tracking-wider">
              Note: Using Pure-Python Fallback Engine due to system restrictions
            </p>
          )}
        </div>
        <div className="flex items-center gap-3">
           <button 
            onClick={handleDownload}
            className="p-2 rounded-lg bg-slate-800 hover:bg-slate-700 text-slate-300 transition-colors" 
            title="Download JSON Report"
           >
             <Download className="w-5 h-5" />
           </button>
           <button 
            onClick={handleShare}
            className="flex items-center gap-2 px-4 py-2 rounded-xl bg-indigo-600 hover:bg-indigo-500 text-white font-medium transition-all shadow-lg shadow-indigo-500/10 active:scale-95"
           >
             {copied ? <Check className="w-4 h-4" /> : <Copy className="w-4 h-4" />}
             {copied ? 'Copied!' : 'Share Analysis'}
           </button>
        </div>
      </div>

      {/* Summary Card */}
      <div className="relative group">
        <div className="absolute -inset-0.5 bg-gradient-to-r from-indigo-500 to-purple-600 rounded-3xl blur opacity-10 group-hover:opacity-20 transition duration-1000"></div>
        <div className="relative p-8 rounded-3xl glass-morphism space-y-6">
          <div className="flex items-center gap-3">
            <Sparkles className="w-6 h-6 text-amber-400 animate-pulse" />
            <h3 className="text-lg font-bold bg-gradient-to-r from-white to-slate-400 bg-clip-text text-transparent">AI Generated Summary</h3>
          </div>
          <div className="relative">
            <Quote className="absolute -top-4 -left-4 w-12 h-12 text-white/5 -z-10" />
            <p className="text-xl leading-relaxed text-slate-200 font-medium italic">
               "{summary}"
            </p>
          </div>
        </div>
      </div>

      {/* Entities Grid */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
        <EntityCard title="Names" entities={entities.names} type="names" />
        <EntityCard title="Dates" entities={entities.dates} type="dates" />
        <EntityCard title="Organizations" entities={entities.organizations} type="organizations" />
        <EntityCard title="Amounts" entities={entities.amounts} type="amounts" />
      </div>

      {!entities.names.length && !entities.dates.length && !entities.organizations.length && !entities.amounts.length && (
         <div className="p-8 rounded-2xl border border-dashed border-slate-700 text-center space-y-2">
            <p className="text-slate-400 italic">No specific named entities were identified in this document.</p>
         </div>
      )}
    </div>
  );
};

export default ResultDisplay;
